### ISSUE TITLE
Did not work in Python 3.6

### ISSUE THREAD

**Issue by manhcuong0312** [txt2tags/txt2tags-python3#1]
I got the following errors when try converting the ChangeLog.t2t file.
![error](https://user-images.githubusercontent.com/40142033/41817675-5ece3c50-778f-11e8-8ebb-108ee68491a3.png)

**Comment by aureliojargas** [comment]
Hi @dangmanhcuong87, the official txt2tags repository at https://github.com/txt2tags/txt2tags
is now working in both Python 2 and Python 3, please use that instead of this repository.
